# syntax=docker/dockerfile:1

FROM node:20-bookworm-slim
WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["sh","./scripts/dev-docker.sh"]
