services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5015:5015"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 5015
    restart: unless-stopped
