services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "800"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "800"
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
