const fullPlatformFeatures = [
  "Lead Management (capture, assign, track)",
  "Contact & Customer Management",
  "Sales Pipeline & Deal Tracking",
  "Tasks, Follow-ups & Reminders",
  "Click-to-Call + Call Logs",
  "Call Recording Tracking",
  "WhatsApp Chat Integration",
  "WhatsApp Automation (templates, broadcast)",
  "Quotation & Invoice Management",
  "Payment Tracking",
  "Ticketing & Support System",
  "Dashboard & Reports",
  "Analytics & Performance Tracking",
  "Role-Based Access Control (RBAC)",
  "User Activity Logs (Audit)",
  "API & Integrations (Ads, Telephony, Webhooks)",
  "Workflow Automation",
  "Multi-User Collaboration",
];

export const pricingPlans = [
  {
    name: "Starter",
    price: {
      quarterly: 1399,
      semiannual: 1299,
      annual: 1199,
    },
    total: {
      quarterly: "\u20B94,197",
      semiannual: "\u20B97,794",
      annual: "\u20B914,388",
    },
    users: "3-5 Users",
    featureSectionTitle: "Features (Full Platform)",
    description: "Full CRM platform for smaller teams ready to centralize sales and support.",
    features: [
      "Lead Management",
      "Contact & Customer Management",
      "Sales Pipeline & Deal Tracking",
      "Tasks, Follow-ups & Reminders",
      "WhatsApp Chat Integration",
      "Dashboard & Reports",
    ],
    fullFeatures: fullPlatformFeatures,
    support: [
      "Standard Support",
      "Response Time: 24-48 hrs",
      "Basic Onboarding (1 session)",
    ],
    buttonText: "Get Started",
    highlighted: false,
    outline: true,
  },
  {
    name: "Growth",
    price: {
      quarterly: 1199,
      semiannual: 1099,
      annual: 999,
    },
    total: {
      quarterly: "\u20B93,597",
      semiannual: "\u20B96,594",
      annual: "\u20B911,988",
    },
    users: "6-10 Users",
    featureSectionTitle: "Includes",
    description: "Everything in Starter with stronger performance and faster support for growing teams.",
    features: [
      "Everything in Starter",
      "Improved System Performance",
      "Priority Resource Allocation",
      "Priority Support",
      "Guided Onboarding",
    ],
    fullFeatures: [
      ...fullPlatformFeatures,
      "Improved System Performance",
      "Priority Resource Allocation",
    ],
    support: [
      "Priority Support",
      "Response Time: 12-24 hrs",
      "Guided Onboarding (2-3 sessions)",
    ],
    buttonText: "Get Started",
    highlighted: true,
    badge: "Most Popular",
  },
  {
    name: "Scale",
    price: {
      quarterly: 999,
      semiannual: 949,
      annual: 899,
    },
    total: {
      quarterly: "\u20B92,997",
      semiannual: "\u20B95,694",
      annual: "\u20B910,788",
    },
    users: "10+ Users",
    featureSectionTitle: "Includes",
    description: "Built for larger operations that need dedicated resources and tighter service commitments.",
    features: [
      "Everything in Starter",
      "High Priority Infrastructure",
      "Dedicated Resource Allocation",
      "Dedicated Account Manager",
      "Full Onboarding + Training",
    ],
    fullFeatures: [
      ...fullPlatformFeatures,
      "High Priority Infrastructure",
      "Dedicated Resource Allocation",
    ],
    support: [
      "SLA Support (4-8 hrs)",
      "Dedicated Account Manager",
      "Full Onboarding + Training",
    ],
    buttonText: "Contact Sales",
    highlighted: false,
  },
];
